-- Arregla HTTP 400: null value in column "id" of relation "solicitudes"
-- La tabla creada a mano suele tener id bigint NOT NULL sin autoincremento.
-- SQL Editor → New query → pegar → Run
-- https://supabase.com/dashboard/project/vtwyqhxfuiwjvzgptecb/sql/new

do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'solicitudes'
      and column_name = 'id'
  ) then
    raise exception 'No existe la columna public.solicitudes.id';
  end if;

  -- Postgres 10+: identidad en la misma columna bigint
  begin
    alter table public.solicitudes
      alter column id add generated by default as identity;
    raise notice 'id configurado como IDENTITY';
  exception
    when others then
      create sequence if not exists public.solicitudes_id_seq;
      alter table public.solicitudes
        alter column id set default nextval('public.solicitudes_id_seq');
      alter sequence public.solicitudes_id_seq owned by public.solicitudes.id;
      perform setval(
        'public.solicitudes_id_seq',
        coalesce((select max(id) from public.solicitudes), 0) + 1,
        false
      );
      raise notice 'id configurado con secuencia solicitudes_id_seq';
  end;
end $$;
