# -*- coding: utf-8 -*-
"""Cookies policy sections 1-3, 5-6 (section 4 generated by build script)."""

COOKIES_SECTIONS = {
    "es": {
        "title": "POLÍTICA DE COOKIES",
        "sections": [
            {"h": "1. Uso de cookies", "ps": [
                "El sitio web de Burguar Dreams (el Sitio Web), propiedad de Burguar Dreams S.L., utiliza cookies. Una cookie es un archivo que se descarga en tu ordenador al acceder a determinadas páginas web. Las cookies permiten a un sitio web, entre otras cosas, almacenar y recuperar información sobre los hábitos de navegación del usuario o de su ordenador y, según la información que contengan y la forma en que utilice su ordenador, pueden utilizarse para reconocer al usuario. Además, mejoran la experiencia de navegación, ya que permiten al sitio web ofrecer al usuario información que pueda ser de su interés en función del uso que haga del contenido del sitio web.",
            ]},
            {"h": "2. Consentimiento", "ps": [
                "Las cookies que utilizamos no almacenan ningún dato personal ni ningún tipo de información que pueda identificarle, a menos que desee registrarse voluntariamente para utilizar los servicios que ponemos a su disposición o para recibir información sobre apartamentos y servicios de su interés. Al navegar por primera vez, aparecerá un banner que explica el uso de cookies.",
            ]},
            {"h": "3. Tipos y finalidad de las cookies", "ps": [
                "Las cookies, según su permanencia, se pueden clasificar de la siguiente manera:",
            ], "list": [
                "<strong>Cookies de sesión:</strong> caducan cuando el usuario cierra el navegador.",
                "<strong>Cookies persistentes:</strong> caducan cuando se cumple la finalidad para la que se utilizan o cuando se eliminan manualmente.",
            ], "ps2": [
                "En nuestro sitio web utilizamos diferentes tipos de cookies para mejorar la experiencia de nuestros usuarios.",
                "Las <strong>cookies necesarias</strong> son imprescindibles para habilitar las funciones básicas del sitio, como la gestión de sus preferencias de consentimiento. Estas cookies no almacenan ningún dato que permita identificarle personalmente.",
                "Las <strong>cookies funcionales</strong> ayudan a realizar ciertas funciones, como compartir contenido en redes sociales u otras funciones de terceros.",
                "Las <strong>cookies analíticas</strong> se utilizan para comprender cómo interactúan los visitantes con el sitio web, proporcionando información sobre métricas como el número de visitantes, la tasa de rebote, la fuente de tráfico, etc.",
                "Las <strong>cookies publicitarias</strong> se utilizan para ofrecer a los visitantes anuncios personalizados basados en las páginas que han visitado anteriormente y para analizar la eficacia de las campañas publicitarias.",
            ]},
            None,  # section 4 injected by build script
            {"h": "5. Modificaciones", "ps": [
                "Las cookies de este sitio web o esta política pueden actualizarse, por lo que le recomendamos que las revise periódicamente.",
            ]},
            {"h": "6. Lista de cookies"},
        ],
    },
    "ca": {
        "title": "POLÍTICA DE GALETES",
        "sections": [
            {"h": "1. Ús de galetes", "ps": [
                "El lloc web de Burguar Dreams (el Lloc Web), propietat de Burguar Dreams S.L., utilitza galetes. Una galeta és un fitxer que es descarrega al vostre ordinador en accedir a determinades pàgines web. Les galetes permeten a un lloc web, entre altres coses, emmagatzemar i recuperar informació sobre els hàbits de navegació de l'usuari o del seu ordinador i, segons la informació que continguin i la forma en què utilitzi el seu ordinador, es poden utilitzar per reconèixer l'usuari. A més, milloren l'experiència de navegació, ja que permeten al lloc web oferir a l'usuari informació que pugui ser del seu interès en funció de l'ús que faci del contingut del lloc web.",
            ]},
            {"h": "2. Consentiment", "ps": [
                "Les galetes que utilitzem no emmagatzemen cap dada personal ni cap tipus d'informació que pugui identificar-vos, llevat que desitgeu registrar-vos voluntàriament per utilitzar els serveis que posem a la vostra disposició o per rebre informació sobre apartaments i serveis del vostre interès. En navegar per primera vegada, apareixerà un banner que explica l'ús de galetes.",
            ]},
            {"h": "3. Tipus i finalitat de les galetes", "ps": [
                "Les galetes, segons la seva permanència, es poden classificar de la manera següent:",
            ], "list": [
                "<strong>Galetes de sessió:</strong> caduquen quan l'usuari tanca el navegador.",
                "<strong>Galetes persistents:</strong> caduquen quan es compleix la finalitat per a la qual s'utilitzen o quan s'eliminen manualment.",
            ], "ps2": [
                "Al nostre lloc web utilitzem diferents tipus de galetes per millorar l'experiència dels nostres usuaris.",
                "Les <strong>galetes necessàries</strong> són imprescindibles per habilitar les funcions bàsiques del lloc, com la gestió de les vostres preferències de consentiment. Aquestes galetes no emmagatzemen cap dada que permeti identificar-vos personalment.",
                "Les <strong>galetes funcionals</strong> ajuden a realitzar certes funcions, com compartir contingut a xarxes socials o altres funcions de tercers.",
                "Les <strong>galetes analítiques</strong> s'utilitzen per comprendre com interactuen els visitants amb el lloc web, proporcionant informació sobre mètriques com el nombre de visitants, la taxa de rebot, la font de trànsit, etc.",
                "Les <strong>galetes publicitàries</strong> s'utilitzen per oferir als visitants anuncis personalitzats basats en les pàgines que han visitat anteriorment i per analitzar l'eficàcia de les campanyes publicitàries.",
            ]},
            None,
            {"h": "5. Modificacions", "ps": [
                "Les galetes d'aquest lloc web o aquesta política poden actualitzar-se, per la qual cosa us recomanem que les reviseu periòdicament.",
            ]},
            {"h": "6. Llista de galetes"},
        ],
    },
    "en": {
        "title": "COOKIE POLICY",
        "sections": [
            {"h": "1. Use of cookies", "ps": [
                "The Burguar Dreams website (the Website), owned by Burguar Dreams S.L., uses cookies. A cookie is a file that is downloaded to your computer when you access certain web pages. Cookies allow a website, among other things, to store and retrieve information about the browsing habits of the user or their computer and, depending on the information they contain and the way the computer is used, they may be used to recognise the user. They also improve the browsing experience, as they allow the website to offer the user information that may be of interest based on their use of the website content.",
            ]},
            {"h": "2. Consent", "ps": [
                "The cookies we use do not store any personal data or any type of information that can identify you, unless you voluntarily register to use the services we make available to you or to receive information about apartments and services of interest to you. When browsing for the first time, a banner explaining the use of cookies will appear.",
            ]},
            {"h": "3. Types and purpose of cookies", "ps": [
                "Cookies, depending on their duration, can be classified as follows:",
            ], "list": [
                "<strong>Session cookies:</strong> expire when the user closes the browser.",
                "<strong>Persistent cookies:</strong> expire when the purpose for which they are used is fulfilled or when they are manually deleted.",
            ], "ps2": [
                "On our website we use different types of cookies to improve our users' experience.",
                "The <strong>necessary cookies</strong> are essential to enable the basic functions of the site, such as managing your consent preferences. These cookies do not store any data that allows you to be personally identified.",
                "The <strong>functional cookies</strong> help perform certain functions, such as sharing content on social networks or other third-party features.",
                "The <strong>analytics cookies</strong> are used to understand how visitors interact with the website, providing information on metrics such as number of visitors, bounce rate, traffic source, etc.",
                "The <strong>advertising cookies</strong> are used to offer visitors personalised ads based on pages they have previously visited and to analyse the effectiveness of advertising campaigns.",
            ]},
            None,
            {"h": "5. Amendments", "ps": [
                "The cookies on this website or this policy may be updated, so we recommend that you review them periodically.",
            ]},
            {"h": "6. Cookie list"},
        ],
    },
    "fr": {
        "title": "POLITIQUE DE COOKIES",
        "sections": [
            {"h": "1. Utilisation des cookies", "ps": [
                "Le site web de Burguar Dreams (le Site Web), propriété de Burguar Dreams S.L., utilise des cookies. Un cookie est un fichier qui se télécharge sur votre ordinateur lorsque vous accédez à certaines pages web. Les cookies permettent à un site web, entre autres, de stocker et de récupérer des informations sur les habitudes de navigation de l'utilisateur ou de son ordinateur et, selon les informations qu'ils contiennent et la façon dont l'ordinateur est utilisé, peuvent servir à reconnaître l'utilisateur. De plus, ils améliorent l'expérience de navigation, car ils permettent au site web d'offrir à l'utilisateur des informations susceptibles de l'intéresser en fonction de son utilisation du contenu du site.",
            ]},
            {"h": "2. Consentement", "ps": [
                "Les cookies que nous utilisons ne stockent aucune donnée personnelle ni aucun type d'information permettant de vous identifier, sauf si vous souhaitez vous inscrire volontairement pour utiliser les services que nous mettons à votre disposition ou pour recevoir des informations sur des appartements et services correspondant à vos intérêts. Lors de la première navigation, une bannière expliquant l'utilisation des cookies apparaîtra.",
            ]},
            {"h": "3. Types et finalité des cookies", "ps": [
                "Les cookies, selon leur durée, peuvent être classés de la manière suivante :",
            ], "list": [
                "<strong>Cookies de session :</strong> expirent lorsque l'utilisateur ferme le navigateur.",
                "<strong>Cookies persistants :</strong> expirent lorsque la finalité pour laquelle ils sont utilisés est atteinte ou lorsqu'ils sont supprimés manuellement.",
            ], "ps2": [
                "Sur notre site web, nous utilisons différents types de cookies pour améliorer l'expérience de nos utilisateurs.",
                "Les <strong>cookies nécessaires</strong> sont indispensables pour activer les fonctions de base du site, comme la gestion de vos préférences de consentement. Ces cookies ne stockent aucune donnée permettant de vous identifier personnellement.",
                "Les <strong>cookies fonctionnels</strong> aident à réaliser certaines fonctions, comme le partage de contenu sur les réseaux sociaux ou d'autres fonctionnalités tierces.",
                "Les <strong>cookies analytiques</strong> sont utilisés pour comprendre comment les visiteurs interagissent avec le site web, en fournissant des informations sur des métriques telles que le nombre de visiteurs, le taux de rebond, la source de trafic, etc.",
                "Les <strong>cookies publicitaires</strong> sont utilisés pour proposer aux visiteurs des annonces personnalisées basées sur les pages qu'ils ont visitées précédemment et pour analyser l'efficacité des campagnes publicitaires.",
            ]},
            None,
            {"h": "5. Modifications", "ps": [
                "Les cookies de ce site web ou cette politique peuvent être mis à jour ; nous vous recommandons donc de les consulter périodiquement.",
            ]},
            {"h": "6. Liste des cookies"},
        ],
    },
    "de": {
        "title": "COOKIE-RICHTLINIE",
        "sections": [
            {"h": "1. Verwendung von Cookies", "ps": [
                "Die Website von Burguar Dreams (die Website), Eigentum der Burguar Dreams S.L., verwendet Cookies. Ein Cookie ist eine Datei, die auf Ihren Computer heruntergeladen wird, wenn Sie auf bestimmte Webseiten zugreifen. Cookies ermöglichen es einer Website unter anderem, Informationen über die Surfgewohnheiten des Nutzers oder seines Computers zu speichern und abzurufen und können, je nach den enthaltenen Informationen und der Art der Computernutzung, zur Erkennung des Nutzers verwendet werden. Darüber hinaus verbessern sie das Surferlebnis, da sie es der Website ermöglichen, dem Nutzer Informationen anzubieten, die je nach Nutzung der Website-Inhalte für ihn von Interesse sein können.",
            ]},
            {"h": "2. Einwilligung", "ps": [
                "Die von uns verwendeten Cookies speichern keine personenbezogenen Daten oder Informationen, die Sie identifizieren könnten, es sei denn, Sie registrieren sich freiwillig, um die von uns angebotenen Dienste zu nutzen oder Informationen über Apartments und Dienstleistungen zu erhalten, die Sie interessieren. Beim ersten Besuch erscheint ein Banner, das die Verwendung von Cookies erklärt.",
            ]},
            {"h": "3. Arten und Zweck der Cookies", "ps": [
                "Cookies können je nach Dauer wie folgt eingeteilt werden:",
            ], "list": [
                "<strong>Sitzungs-Cookies:</strong> laufen ab, wenn der Nutzer den Browser schließt.",
                "<strong>Dauerhafte Cookies:</strong> laufen ab, wenn der Zweck, für den sie verwendet werden, erfüllt ist, oder wenn sie manuell gelöscht werden.",
            ], "ps2": [
                "Auf unserer Website verwenden wir verschiedene Arten von Cookies, um das Erlebnis unserer Nutzer zu verbessern.",
                "Die <strong>notwendigen Cookies</strong> sind unerlässlich, um die Grundfunktionen der Website zu aktivieren, wie die Verwaltung Ihrer Einwilligungspräferenzen. Diese Cookies speichern keine Daten, die eine persönliche Identifizierung ermöglichen.",
                "Die <strong>funktionalen Cookies</strong> helfen bei bestimmten Funktionen, wie dem Teilen von Inhalten in sozialen Netzwerken oder anderen Funktionen Dritter.",
                "Die <strong>analytischen Cookies</strong> werden verwendet, um zu verstehen, wie Besucher mit der Website interagieren, und liefern Informationen zu Kennzahlen wie Besucherzahl, Absprungrate, Traffic-Quelle usw.",
                "Die <strong>Werbe-Cookies</strong> werden verwendet, um Besuchern personalisierte Anzeigen basierend auf zuvor besuchten Seiten anzuzeigen und die Wirksamkeit von Werbekampagnen zu analysieren.",
            ]},
            None,
            {"h": "5. Änderungen", "ps": [
                "Die Cookies dieser Website oder diese Richtlinie können aktualisiert werden; wir empfehlen daher, sie regelmäßig zu überprüfen.",
            ]},
            {"h": "6. Cookie-Liste"},
        ],
    },
    "it": {
        "title": "INFORMATIVA SUI COOKIE",
        "sections": [
            {"h": "1. Uso dei cookie", "ps": [
                "Il sito web di Burguar Dreams (il Sito Web), di proprietà di Burguar Dreams S.L., utilizza i cookie. Un cookie è un file che viene scaricato sul vostro computer quando accedete a determinate pagine web. I cookie consentono a un sito web, tra l'altro, di memorizzare e recuperare informazioni sulle abitudini di navigazione dell'utente o del suo computer e, a seconda delle informazioni che contengono e del modo in cui viene utilizzato il computer, possono essere utilizzati per riconoscere l'utente. Inoltre, migliorano l'esperienza di navigazione, poiché permettono al sito web di offrire all'utente informazioni che possono essere di suo interesse in base all'uso che fa dei contenuti del sito.",
            ]},
            {"h": "2. Consenso", "ps": [
                "I cookie che utilizziamo non memorizzano dati personali né alcun tipo di informazione che possa identificarvi, a meno che non desideriate registrarvi volontariamente per utilizzare i servizi che mettiamo a vostra disposizione o per ricevere informazioni su appartamenti e servizi di vostro interesse. Durante la prima navigazione, apparirà un banner che spiega l'uso dei cookie.",
            ]},
            {"h": "3. Tipi e finalità dei cookie", "ps": [
                "I cookie, in base alla loro durata, possono essere classificati come segue:",
            ], "list": [
                "<strong>Cookie di sessione:</strong> scadono quando l'utente chiude il browser.",
                "<strong>Cookie persistenti:</strong> scadono quando viene raggiunta la finalità per cui sono utilizzati o quando vengono eliminati manualmente.",
            ], "ps2": [
                "Sul nostro sito web utilizziamo diversi tipi di cookie per migliorare l'esperienza dei nostri utenti.",
                "I <strong>cookie necessari</strong> sono indispensabili per abilitare le funzioni di base del sito, come la gestione delle vostre preferenze di consenso. Questi cookie non memorizzano dati che permettano di identificarvi personalmente.",
                "I <strong>cookie funzionali</strong> aiutano a svolgere determinate funzioni, come la condivisione di contenuti sui social network o altre funzionalità di terze parti.",
                "I <strong>cookie analitici</strong> vengono utilizzati per capire come i visitatori interagiscono con il sito web, fornendo informazioni su metriche come il numero di visitatori, la percentuale di rimbalzo, la fonte di traffico, ecc.",
                "I <strong>cookie pubblicitari</strong> vengono utilizzati per offrire ai visitatori annunci personalizzati basati sulle pagine visitate in precedenza e per analizzare l'efficacia delle campagne pubblicitarie.",
            ]},
            None,
            {"h": "5. Modifiche", "ps": [
                "I cookie di questo sito web o la presente informativa possono essere aggiornati; vi consigliamo pertanto di consultarli periodicamente.",
            ]},
            {"h": "6. Elenco dei cookie"},
        ],
    },
}
